name: build fuzzbox

on:
  push:
    branches:
      - main
      - 2023-01-10-fuzz

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build -t holochain/fuzzbox:holochain-serialization .
      - run: docker push holochain/fuzzbox:holochain-serialization